### ISSUE TITLE
TensorRT plugin error: CUDA error 222 ....../YoloLayer_TRT_v7.0/yololayer.cu:42Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by JJLimmm** [nanmi/yolov7-pose#13]
Hi @nanmi , wonder if you know the solution to this error.
I just exported the pose model to onnx, and ran the command 
`/usr/src/tensorrt/bin/trtexec --onnx=../yolov7-w6-pose-sim.onnx --fp16 --saveEngine=yolov7-w6-pose-sim-fp16.engine --plugins=./YoloLayer_TRT_v7.0/build/libyolo.so`.
Below shows the output of the command...
![tensorrt_error](https://user-images.githubusercontent.com/79782049/212867771-ce77a9c9-2599-45b6-bbd3-15512c03cc7d.png)

I am currently running on the following versions... 
RTX 2060
CUDA 11.6
TensorRT 8.5.1.7
Torch 1.10.0

**Comment by JJLimmm** [comment]
Hi all, managed to export the yolov7-w6-pose-sim.onnx (the model network weights after running "add_custom_yolo_op.py" file) to a Tensor RT engine file.

Steps i did (I installed with Anaconda3 base env active and on a RTX 2060 GPU):
1. Reinstall CUDA (Driver 525.60.13 and Toolkit 11.6) using tar file method / cuDNN [v8.5](https://developer.nvidia.com/rdp/cudnn-archive#:~:text=Local%20Installers%20for%20Windows%20and%20Linux%2C%20Ubuntu(x86_64%2C%20armsbsa)) 
2. Reinstall TensorRT-8.5.1.7 (version 8.5.1 GA) , tar file installation method
3. add `TensorRT-8.5.1.7/lib` folder to PATH [export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/<path_to_where_tensorRT_is_installed>
4. follow the [steps 6 to 9](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-851/install-guide/index.html#installing-tar:~:text=Install%20the%20Python%20TensorRT%20wheel%20file.) in both anaconda base and your desired working environment. 

Once Done, Follow the steps in this repo, and you can get yout engine file.

**Comment by zzz3bbb3** [comment]
CUDA error code 222 indicates a CUDA driver Software bug. This error code usually indicates that sufficient video memory cannot be allocated. Possible reasons include:

Insufficient graphics memory: Your program is attempting to allocate more memory than available graphics memory. This may be because your model or data is too large to accommodate the currently available graphics memory. You can try reducing the size of the model, reducing the batch size, or using a smaller dataset.

Video memory fragmentation: Due to video memory fragmentation, where there are many small unused spaces between allocated video memory blocks, it is impossible to allocate a large continuous video memory block. This may be because your program has repeatedly performed multiple memory allocation and release operations. Before using graphics memory, you can try using torch. cuda. empty_ Cache() to clear the cache and release some unused graphics memory.

Driver or CUDA version issue: Some CUDA errors may be related to incompatible drivers or CUDA versions. You can try updating your CUDA driver or downgrade to a driver that is compatible with your CUDA version.

If you encounter CUDA error code 222, it is recommended that you check your code and environment configuration to ensure proper allocation and use of graphics memory, and to ensure compatibility between the driver and CUDA version. If the problem persists, you may need to examine your code and model in more detail to identify other possible issues.
